### ISSUE TITLE
Whitespace after wrong quote mark is swallowed

### ISSUE THREAD

**Issue by albbas** [divvun/divvun-gramcheck-web#38]
`don" mii` is corrected to `don”mii`
Tested in Google Docs/Firefox/Linux

**Comment by unhammer** [comment]
what pipe is this, se-smegramrelease?

**Comment by snomos** [comment]
It is the default one, which should be `smegramrelease`.

**Comment by unhammer** [comment]
```
$ echo 'don" mii' | divvun-checker -l se
{"errs":[["\" mii",3,8,"punct-aistton-left","Boasttuaisttonmearkkat",["”mii"],"Aisttonmearkkat"]],"text":"don\" mii"}

$ echo 'don" mii' |bash smegramrelease.sh 
"<don>"
        "don" Pron Sem/Hum Pers Sg2 Nom <W:0.0> <firstCohort> @HNOUN
"<">"
        """ PUNCT <W:0.0> &punct-aistton-left ID:2 R:RIGHT:3
punct-aistton-left
        """ PUNCT <W:0.0> "”mii"S &punct-aistton-left &SUGGESTWF ID:2 R:RIGHT:3
punct-aistton-left
        "”" PUNCT RIGHT Err/Orth <W:0.0> ID:2 R:RIGHT:3
: 
"<mii>"
        "mii" Pron Indef Sg Nom <W:0.0> <LastCohort> &LINK &punct-aistton-left ID:3
punct-aistton-left
        "mii" Pron Rel Sg Nom <W:0.0> <LastCohort> &LINK &punct-aistton-left ID:3
punct-aistton-left
        "mun" Pron Sem/Hum Pers Pl1 Nom <W:0.0> <LastCohort> &LINK &punct-aistton-left ID:3
punct-aistton-left
:\n
```

The rule that adds the suggestion
```
# Generer forslag for hermeteikn på _venstre_ side:
COPY:punct-aistton-left-sugg KEEPORDER (VSTR:"”$1"S &SUGGESTWF) TARGET (&punct-aistton-left) IF
```
https://github.com/giellalt/lang-sme/blob/6840e25893ae7d14ae76e545aa2cf01ea532c85d/tools/grammarcheckers/grammarchecker-release.cg3#L9232-L9233

puts the suggestion on (the left of) `mii` since `mii` got the `&punct-aistton-left` tag. 

So why didn't `don"` get `&punct-aistton-right` instead? There is no such rule – the [rules](https://github.com/giellalt/lang-sme/blob/main/tools/grammarcheckers/grammarchecker-release.cg3#L9200..L9203) either assume we have wrong aisttons on both sides of the word, or on the left (only "»" can get `&punct-aistton-right`). 

The reason is probably that we don't in CG know where the space is. That could be solved by adding a tag to the PUNCT cohort with blanktagger, then the rules could just check for space-to-the-left or space-to-the-right or something like that and choose between punct-aistton-left vs -right that way.

**Comment by snomos** [comment]
This works now in both MS Word and GDocs.
