### ISSUE TITLE
Googledoc grc plugin does not find grammarchecker (but MS Word plugin works)

### ISSUE THREAD

**Issue by Trondtr** [divvun/divvun-gramcheck-web#70]
To repeat:
Have the grammarchecker installed in Google docs as explained on divvun.no
Open document in Google docs. Write something, send to check (click the extension Divvun grammarchecker).

A red alert box shows up saying "Ikke funnet" (the English message thus probably "Not found". The links to detailed feedback only repeats "Ikke funnet." Neither the right hand side pane nor any corrections show up.

MS Word plugin works as normal.

**Comment by snomos** [comment]
This is a serous bug, and needs immediate attention. Please have a look @Eijebong and @bbqsrc

**Comment by snomos** [comment]
Any progress on this one, @Eijebong? Here's what happens when trying to install the extension in GDocs:

<img width="1044" alt="Skjermbilde 2022-09-21 kl  15 03 08" src="https://user-images.githubusercontent.com/1255285/191499140-07187690-4fd9-4d80-a475-ba8e7dd06675.png">

When clicking **FORTSETT** (=«Continue»), I get this message:

<img width="762" alt="Skjermbilde 2022-09-21 kl  15 03 14" src="https://user-images.githubusercontent.com/1255285/191499239-407987e7-39ab-406e-bea7-8c45fcb9d31c.png">

So something is clearly missing.

**Comment by snomos** [comment]
From @fry :

> From the best of my memory, the addon listing itself is in one of these Google Cloud organisations that is accessible by the Divvun account. When I try to use it in Google Docs now, the Google Apps Script is not found. That might have been in my account and that might have expired. The reference to the script is set by the Google Apps Script ID in the Google Cloud Org.
> It might be as easy as pushing the script on a new account (https://github.com/divvun/divvun-gramcheck-web/blob/master/google/package.json#L7) and then fixing the script reference in the Google Cloud project.

@Eijebong please have a look 😃

**Comment by snomos** [comment]
This is now fixed.
